name: build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libappindicator3-dev xvfb
      - run: flutter config --enable-linux-desktop
      - run: cd example && flutter build linux -v
      - run: cd example && xvfb-run -a flutter test integration_test -v
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - run: flutter config --enable-macos-desktop
      - run: cd example &&  flutter build macos -v
      # Blocked by https://github.com/flutter/flutter/issues/118469
      # - run: cd example && flutter test integration_test -v
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - run: cd example && flutter build windows -v
      - run: cd example && flutter test integration_test -v
