name: test

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, reopened]

jobs:
  integration_test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.32.0"
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev ayatana-appindicator3-0.1 xvfb
      - uses: bluefireteam/melos-action@v3
      - working-directory: ./packages/window_manager/example
        run: xvfb-run -a flutter test integration_test -v
  integration_test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.32.0"
      - uses: bluefireteam/melos-action@v3
      # Blocked by https://github.com/flutter/flutter/issues/118469
      # - working-directory: ./packages/window_manager/example
      #   run: flutter test integration_test -v
  integration_test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.32.0"
      - uses: bluefireteam/melos-action@v3
      - working-directory: ./packages/window_manager/example
        run: flutter test integration_test -v
